version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: colnio/sampledb_pg 
    hostname: localhost
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    # container-name: go-web
    image: colnio/sampledb:v0.0.1
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - "80:80"
    volumes:
      - web-data:/uploads
    restart: unless-stopped

volumes:
  postgres-data:
  web-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .